method: bayes

early_terminate:
  type: hyperband
  min_iter: 2

metric:
  name: cum. accuracy
  goal: maximize

parameters:
  sinkhorn_reg:
    value: 0.001409
  nu:
    value: 447.24
  mu:
    value: 442.66
  components:
    min: 1
    max: 30
